### ISSUE TITLE
失恋场

### ISSUE THREAD

**Issue by HoshinoTented** [HoshinoTented/LuoGuAPI#20]

**Comment by HoshinoTented** [comment]
失恋场可海星

**Comment by Himself65** [comment]
what's this meaning for?

**Comment by HoshinoTented** [comment]
> what's this meaning for?
Please speak Chinese

**Comment by HoshinoTented** [comment]
就是 [试炼场](https://www.luogu.org/training/mainpage)

**Comment by Himself65** [comment]
@HoshinoTented 好的好的

**Comment by HoshinoTented** [comment]
还要实现 `完成任务啦` 按钮和 `跳过人物` 按钮

**Comment by HoshinoTented** [comment]
需要重构 [PracticeBlock](https://github.com/HoshinoTented/LuoGuAPI/blob/master/src/main/kotlin/org/hoshino9/luogu/practice/PracticeBlock.kt)

**Comment by HoshinoTented** [comment]
真的厉害
打印用了42.5秒...
![image](https://user-images.githubusercontent.com/25280943/48967760-88d3c600-f020-11e8-9d3a-bc1809946d44.png)

**Comment by HoshinoTented** [comment]
剩下 `TrainingPage` 了

**Comment by xczy** [comment]
tql

**Comment by HoshinoTented** [comment]
> tql

欢迎大佬光临
