### ISSUE TITLE
弃坑

### ISSUE THREAD

**Issue by HoshinoTented** [HoshinoTented/LuoGuAPI#32]
原本没有改动的代码重新运行出现了很多问题
估计是 **您谷** 了
虽然不知道目的是什么
但是星野野觉得 **您谷** 只是想让星野野弃坑
好的
那就这样做
吧

**Comment by Himself65** [comment]
xyy不哭，摸摸

**Comment by HoshinoTented** [comment]
第一次解决: 访问请求需要 referer header, cookie 需要 _uid

**Comment by HoshinoTented** [comment]
星野野觉得还有第二次第三次。。

**Comment by HoshinoTented** [comment]
致谢: https://github.com/pillarjs/understanding-csrf/blob/master/README_zh.md

**Comment by HoshinoTented** [comment]
让你谷先清净几天吧... 
星野野也要静下心来学习haskell了QAQ

**Comment by HoshinoTented** [comment]
幼稚的想法, 星野野真是太自以为是了

**Comment by ice1000** [comment]
幼稚的想法, 星野野真是太自以为是了
