### ISSUE TITLE
关于星野野本人对这个项目的一些看法

### ISSUE THREAD

**Issue by HoshinoTented** [HoshinoTented/LuoGuAPI#35]
首先。。  
现在并不是很想来搞这个项目  
`LuoGuAPI` 就仅仅只是从你谷的页面人肉找到 `API` 或者 `Parse HTML`  
这十分枯燥, 没有任何的技术含量  
星野野也最讨厌这种工作  
所以是有那么一丝 `Delete Project` 的想法的
不过想了想还是算了, 可能有其他人需要这个项目(怎么可能会有啊, 这么LAJI的项目有谁会看  
好了好了, 大概就是这样子了

**Comment by Himself65** [comment]
摸摸星野野

**Comment by HoshinoTented** [comment]
@Himself65 被摸了

**Comment by ice1000** [comment]
你看，现在火了
等你功能做完我star一下，可以带逛一波
