### ISSUE TITLE
濒临咕咕

### ISSUE THREAD

**Issue by HoshinoTented** [HoshinoTented/LuoGuAPI#42]
因为濒临中考  
所以可能要放一下这个项目去考个好高中~~才怪, 是要去玩翻天~~

**Comment by Himself65** [comment]
星野野又年轻 又可爱 又聚聚

**Comment by HoshinoTented** [comment]
> 星野野又年轻 又可爱 又聚聚

面包包又年轻 又可爱 又聚聚

**Comment by Himself65** [comment]
> > 星野野又年轻 又可爱 又聚聚
> 
> 面包包又年轻 又可爱 又聚聚

并不

**Comment by HoshinoTented** [comment]
> 星野野又年轻 又可爱 又聚聚

并不

**Comment by ice1000** [comment]
萝莉加油
