### ISSUE TITLE
分离功能

### ISSUE THREAD

**Issue by HoshinoTented** [HoshinoTented/LuoGuAPI#47]
将 `题目列表 `，`讨论列表`，`比赛列表` 等功能作为 `扩展` 编写在 `extensions` module 中
需要分离的功能

- [x] 题目列表 (旧版)
- [x] 题目列表 (新版)
- [x] 讨论列表
- [x] 洛谷图床
- [x] 洛谷剪切板
- [x] 试炼场
- [x] ~~犇犇 (尽管该功能已被删除)~~
- [x] 洛谷绘版

**Comment by HoshinoTented** [comment]
洛谷网校好像也用了新的api，星野野或许可以把这个加进去

**Comment by HoshinoTented** [comment]
主要部分仅保留:
* 登录功能
* 用户功能

**Comment by HoshinoTented** [comment]
签到不知道要怎么搞，这个功能很小。。

**Comment by HoshinoTented** [comment]
上学去了

**Comment by ice1000** [comment]
xyy have a good day

**Comment by HoshinoTented** [comment]
but it is a rainy day

**Comment by HoshinoTented** [comment]
算了，犇犇还是删了吧，以后要用的话还能用 git 找回来

**Comment by ice1000** [comment]
算了，犇犇还是删了吧，以后要用的话还能用 xyy 找回来

**Comment by HoshinoTented** [comment]
不！！！！！！！！！！！！！
犇犇什么时候又开了

**Comment by HoshinoTented** [comment]
done
