### ISSUE TITLE
这什么破代码啊，重构吧！

### ISSUE THREAD

**Issue by HoshinoTented** [HoshinoTented/LuoGuAPI#48]

**Comment by HoshinoTented** [comment]
重构那些非常垃圾的代码
非常垃圾的代码 == 所有代码

**Comment by Himself65** [comment]
这什么xyy啊，可爱吧！

**Comment by ice1000** [comment]
这什么mainbug啊，block了吧！

**Comment by ice1000** [comment]
什么代码，哪些地方，xyy要不要我帮你看看？

**Comment by Himself65** [comment]
让我康康！

**Comment by HoshinoTented** [comment]
不要啦，包哥！

**Comment by HoshinoTented** [comment]
比如 `LuoGuUtils`，这东西存在的意义很奇怪
还有很多字段全by lazy的，星野野觉得还是不要lazy比较好

**Comment by Himself65** [comment]
星野野来我家吧，我家蛮大的

by Himself65 Outlook<https://aka.ms/qtex0l>
________________________________
发件人: Hoshino Tented <notifications@github.com>
发送时间: Tuesday, April 30, 2019 1:01:08 PM
收件人: HoshinoTented/LuoGuAPI
抄送: 扩散性百万甜面包; Comment
主题: Re: [HoshinoTented/LuoGuAPI] 这什么破代码啊，重构吧！ (#48)


比如 LuoGuUtils，这东西存在的意义很奇怪
还有很多字段全by lazy的，星野野觉得还是不要lazy比较好

―

**Comment by HoshinoTented** [comment]
跟千里冰冰说悄悄话：这个人看起来怪怪的，不要去

**Comment by Himself65** [comment]
我经常帮助一些翘家的孩子

by Himself65 Outlook<https://aka.ms/qtex0l>
________________________________
发件人: Hoshino Tented <notifications@github.com>
发送时间: Tuesday, April 30, 2019 1:05:01 PM
收件人: HoshinoTented/LuoGuAPI
抄送: 扩散性百万甜面包; Comment
主题: Re: [HoshinoTented/LuoGuAPI] 这什么破代码啊，重构吧！ (#48)


跟千里冰冰说悄悄话：这个人看起来怪怪的，不要去

―

**Comment by HoshinoTented** [comment]
可是星野野不翘家

**Comment by Himself65** [comment]
这么说，你很勇哦

**Comment by HoshinoTented** [comment]
废话，星野野超勇的好不好，这个冰冰就是逊啦

**Comment by Himself65** [comment]
来，给你看个好康的（拉进屋

**Comment by HoshinoTented** [comment]
包哥，你有好多JavaScript代码哦

**Comment by Himself65** [comment]
哦呦，你脸红了？

**Comment by Himself65** [comment]
来，让我看看

**Comment by HoshinoTented** [comment]
不要啦！包哥！

**Comment by ice1000** [comment]
:worried:

**Comment by HoshinoTented** [comment]
搞不懂要怎么重构了

**Comment by HoshinoTented** [comment]
QAQ

**Comment by HoshinoTented** [comment]
😟

**Comment by Himself65** [comment]
mbb不懂Kotlin，故退订此issue

**Comment by ice1000** [comment]
> mbb不懂Kotlin，故退订此issue

Block 了吧

**Comment by ice1000** [comment]
> 搞不懂要怎么重构了

我来改，一天内搞定

**Comment by ice1000** [comment]
#49

**Comment by HoshinoTented** [comment]
#49 
用data class存储数据，用工厂方法提取数据并搞到data class里边
这很好
吗
@ice1000

**Comment by ice1000** [comment]
我觉得很好。但是你这代码好多，我不想去改了……

**Comment by HoshinoTented** [comment]
本小姐自己改，哼！

**Comment by ice1000** [comment]
萝莉加油啊
