### ISSUE TITLE
可否提供公开API服务？或者提供可供部署的Docker镜像？

### ISSUE THREAD

**Issue by masnn** [HoshinoTented/LuoGuAPI#50]
同题。
项目部署较为繁琐，希望提供Dockerfile。

同时，获取题目不需要登陆且有官方API接口（小声）
luogu.org/api/problem/detail/P1000

联系方式：
QQ 3402182471

**Comment by masnn** [comment]
注：此API接口不可使用浏览器打开。
请更改User-Agent。

**Comment by HoshinoTented** [comment]
？？？？
@ice1000

**Comment by HoshinoTented** [comment]
获取题目的确不需要登录，但如果需要获取题目的通过信息就需要

**Comment by HoshinoTented** [comment]
扯远了，星野野并不太会docker，这个issue可能需要等到暑假才能解决

**Comment by Himself65** [comment]
星野野并不太会docker，这个issue可能需要等到暑假才能解决

**Comment by masnn** [comment]
那能否详细说明安装步骤，
我会生成相应的dockerfile。

**Comment by Himself65** [comment]
此项目是一个library，提供各种功能，但具体使用还是**你自己写代码**，所谓的安装应当是app、server的项目

**Comment by HoshinoTented** [comment]
面包包说的对

**Comment by masnn** [comment]
我的意思是，将项目是否打包作为api server在本地运行
________________________________

**Comment by HoshinoTented** [comment]
[惊恐] api server 是什么先进的东西

**Comment by Himself65** [comment]
大概就是我的服务器爬洛谷的数据然后再用api转发出去

by Himself65 Outlook<https://aka.ms/qtex0l>
________________________________
发件人: Hoshino Tented <notifications@github.com>
发送时间: Thursday, May 9, 2019 5:58:46 PM
收件人: HoshinoTented/LuoGuAPI
抄送: 扩散性百万甜面包; Comment
主题: Re: [HoshinoTented/LuoGuAPI] 可否提供公开API服务？或者提供可供部署的Docker镜像？ (#50)


[惊恐] api server 是什么先进的东西

―

**Comment by HoshinoTented** [comment]
[超级大惊恐] 那是要 `Servlet` 了？

**Comment by masnn** [comment]
即在本地运行一个服务器，客户端可以请求该服务器，本地服务器从luogu抓取数据并返回
________________________________

**Comment by HoshinoTented** [comment]
懂了懂了。。

**Comment by HoshinoTented** [comment]
但这需要额外的代码吧

**Comment by masnn** [comment]
嗯，需要稍微封装一下
________________________________

**Comment by HoshinoTented** [comment]
这部分代码不应该是用户写的吗（小声

**Comment by ice1000** [comment]
还有一种办法，做成用stdio交互的，命令行输入参数，输出json数据，服务器啥的都不需要了就

运行就gradlew run

**Comment by HoshinoTented** [comment]
那星野野觉得这部分也应该是用户写（超小声

**Comment by masnn** [comment]
可是我根本不会Kotlin（小声

**Comment by ice1000** [comment]
萝莉啊，你看，潜在的用户诶

不舔一波吗 😉

**Comment by HoshinoTented** [comment]
怎么舔呢
要星野野开个项目写api-server吗

**Comment by HoshinoTented** [comment]
其实也不是不可以（
只是星野野现在没有时间（大概

**Comment by masnn** [comment]
人家不着急呢
（忙于vijos/vj4）

**Comment by HoshinoTented** [comment]
可以试着用 `ktor` ? @ice1000

**Comment by ice1000** [comment]
这很好

**Comment by HoshinoTented** [comment]
这个衣袖是可以的, 顺便针对JavaScript做一下优化 ~~（这样就不用去搞多平台了~~
@Himself65

**Comment by HoshinoTented** [comment]
关于 @masnn 给出的题目接口
根据可靠消息，有更好的接口（就是星野野当前用的这个）

**Comment by HoshinoTented** [comment]
唉，你谷4出来了星野野的项目就没有用处了
QAQ

**Comment by masnn** [comment]
用处还是有的，只不过需要大量重构（

**Comment by Himself65** [comment]
那不就相当于m y y w

**Comment by HoshinoTented** [comment]
https://github.com/HoshinoTented/LuoGuAPIServer

**Comment by HoshinoTented** [comment]
不提供，谢谢
