### ISSUE TITLE
关于 jcenter 的发布

### ISSUE THREAD

**Issue by ice1000** [HoshinoTented/LuoGuAPI#58]
关于 jcenter 的发布 (#39)：

我直接推了两个 commit 到 master，分别是 bintray 发布的配置和 README 里文档的更新。大概有 2-3 个工作日后就可以在 jcenter 里面用到这个库了，因为我发布到 bintray 上的库被送到 jcenter 是需要审核的（反过来，bintray 上就可以直接用了）。如果你现在就想用，那么你需要添加这个 maven 源： https://dl.bintray.com/ice1000/ice1000 （等 jcenter 那边过了就没这东西什么事了）
有个瑕疵是这个库的包名是 `org.hoshino9`，这个包名中没有包含与项目有关的信息，只包含了和作者相关的信息。更好的包名应该是 `org.hoshino9.luoguapi` 之类的，但是我已经手滑发布了就当成一个遗憾吧……

最后，我就这么直接把 0.0.2 发布出去了，萝莉你考虑同步一下版本到 JitPack/GitHub Release 之类的地方去？毕竟虽然我把配置写好了，具体的发布还是得我来（需要用到我的 bintray 账号）

萝莉你读过这个 issue 后就可以把那个 important 的 label 去掉了

**Comment by HoshinoTented** [comment]
有时间再详细看看 QAQ
