### ISSUE TITLE
打算发布 0.0.3 版本了

### ISSUE THREAD

**Issue by HoshinoTented** [HoshinoTented/LuoGuAPI#61]
功能都相对完善了，想发布 0.0.2 版本，先全面测试一下吧

**Comment by HoshinoTented** [comment]
@ice1000 ？

**Comment by ice1000** [comment]
你发布不得靠我给你上传

**Comment by HoshinoTented** [comment]
@ice1000 Please teach me how to publish to jcenter QWQ.

**Comment by HoshinoTented** [comment]
我错了，我应该完全检查的，推送图片的 API 出了 bug，可以删掉之前的 release 吗

**Comment by ice1000** [comment]
> @ice1000 Please teach me how to publish to jcenter QWQ.

首先去注册 bintray 账号吧。然后我跟你说

**Comment by HoshinoTented** [comment]
> > @ice1000 Please teach me how to publish to jcenter QWQ.
> 
> 首先去注册 bintray 账号吧。然后我跟你说

可以 Sign in with Github 吗

**Comment by HoshinoTented** [comment]
0.0.3 版本忘记加 `ProblemPage`，不过不是什么大问题
